💚 Handling failure in Platform Check step
Signed-off-by: Isabella Muerte <63051+slurps-mad-rips@users.noreply.github.com>

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -82,10 +82,11 @@ jobs:
         uses: actions/checkout@v2
       - name: Platform Check
         id: platform
-        run: |
-          test "${{matrix.os}}" = "windows" && echo "::set-outout name=name::windows"
-          test "${{matrix.os}}" = "ubuntu" && echo "::set-output name=name::linux"
-          test "${{matrix.os}}" = "macos" && echo "::set-output name=name::apple"
+        run: >-
+          $(test "${{matrix.os}}" = "windows" && echo "::set-outout name=name::windows")
+          || $(test "${{matrix.os}}" = "ubuntu" && echo "::set-output name=name::linux")
+          || $(test "${{matrix.os}}" = "macos" && echo "::set-output name=name::apple")
+          || echo "::error file=pull-request.yml::Could not find platform for '${{matrix.os}}'"
       - name: Authenticate GitHub CLI
         run: echo ${{github.token}} | gh auth login --with-token
       - name: Retrieve SCCache ID
